#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
reflect_scan.py — Batch reflection scanner and code generator

Scans a directory (recursively) for C++ files annotated with H_CLASS / H_STRUCT,
runs wamr_codegen.py on each one, and generates an aggregated bootstrap .cpp that
calls every module's registration function from a single entry point.

Two operating modes
-------------------
--dry-run   Fast text-grep only (no clang).  Writes the --emit-cmake fragment with
            *predicted* output paths.  Intended for CMake configure-time use via
            execute_process().

(normal)    Full clang AST parse + per-file codegen + bootstrap generation.
            Intended for CMake build-time use via add_custom_command().

Typical CMake workflow
----------------------
  # 1. Configure time — discover candidate files without invoking clang
  execute_process(COMMAND python reflect_scan.py --scan-dir host --out-dir gen
                          --dry-run --emit-cmake gen/reflect_sources.cmake ...)

  # 2. Include the fragment to learn output paths
  include(gen/reflect_sources.cmake)

  # 3. Build time — full codegen, driven by add_custom_command
  add_custom_command(OUTPUT ${REFLECT_GEN_SOURCES} ${REFLECT_BOOTSTRAP_CPP}
      COMMAND python reflect_scan.py --scan-dir host --out-dir gen ...)
"""

from __future__ import annotations

import argparse
import fnmatch
import pathlib
import re
import subprocess
import sys
import textwrap
from typing import List, Tuple

# ---------------------------------------------------------------------------
# Annotation detection — fast text grep, no clang required
# ---------------------------------------------------------------------------

_ANNOT_RE = re.compile(r'\bH_CLASS\b|\bH_STRUCT\b')


def _quick_has_annotations(path: pathlib.Path) -> bool:
    """Return True when the file contains H_CLASS or H_STRUCT anywhere."""
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
        return bool(_ANNOT_RE.search(text))
    except OSError:
        return False


def collect_candidates(
    scan_dir: pathlib.Path,
    extensions: List[str],
    excludes: List[str],
) -> List[pathlib.Path]:
    """Recursively find annotated files with the given extensions."""
    found: List[pathlib.Path] = []
    for ext in extensions:
        for p in sorted(scan_dir.rglob(f"*.{ext}")):
            rel = p.relative_to(scan_dir).as_posix()
            if any(fnmatch.fnmatch(rel, pat) for pat in excludes):
                continue
            if _quick_has_annotations(p):
                found.append(p)
    return found


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def _safe(name: str) -> str:
    return re.sub(r"[^0-9a-zA-Z_]", "_", name)


def register_func_name(stem: str) -> str:
    return f"h_reflect_register_{_safe(stem).lower()}"


def predicted_outputs(
    out_dir: pathlib.Path,
    input_file: pathlib.Path,
) -> Tuple[pathlib.Path, pathlib.Path]:
    stem = input_file.stem
    return (
        out_dir / f"{stem}.reflect.h",
        out_dir / f"{stem}.reflect.cpp",
    )


# ---------------------------------------------------------------------------
# Per-file codegen — delegates to wamr_codegen.py
# ---------------------------------------------------------------------------

def run_codegen(
    codegen_tool: pathlib.Path,
    input_file: pathlib.Path,
    out_h: pathlib.Path,
    out_cpp: pathlib.Path,
    func_name: str,
    clangxx: str,
    std: str,
    includes: List[str],
) -> bool:
    cmd = [
        sys.executable,
        str(codegen_tool),
        "--input",        str(input_file),
        "--out-h",        str(out_h),
        "--out-cpp",      str(out_cpp),
        "--register-func", func_name,
        "--clangxx",      clangxx,
        "--std",          std,
    ]
    for inc in includes:
        cmd.extend(["-I", inc])

    result = subprocess.run(cmd, text=True)
    return result.returncode == 0


# ---------------------------------------------------------------------------
# Bootstrap file generation
# ---------------------------------------------------------------------------

def _cmake_path(p: pathlib.Path) -> str:
    """Convert a path to a forward-slash string safe for CMake."""
    return str(p).replace("\\", "/")


def gen_bootstrap_h(bootstrap_func: str) -> str:
    return textwrap.dedent(f"""\
        #pragma once
        // Auto-generated file — do not edit.
        // Generated by reflect_scan.py

        bool {bootstrap_func}();
    """)


def gen_bootstrap_cpp(
    entries: List[Tuple[str, str]],   # [(reflect_header_name, func_name), ...]
    bootstrap_func: str,
) -> str:
    lines = [
        "// Auto-generated file — do not edit.",
        "// Generated by reflect_scan.py",
        "",
    ]
    for header_name, _ in entries:
        lines.append(f'#include "{header_name}"')
    lines.append("")
    lines.append(f"bool {bootstrap_func}() {{")
    lines.append("    bool ok = true;")
    for _, func in entries:
        lines.append(f"    ok = {func}() && ok;")
    lines.append("    return ok;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CMake fragment generation
# ---------------------------------------------------------------------------

def gen_cmake_fragment(
    input_files:   List[pathlib.Path],
    out_h_files:   List[pathlib.Path],
    out_cpp_files: List[pathlib.Path],
    bootstrap_cpp: pathlib.Path,
    bootstrap_h:   pathlib.Path,
) -> str:
    def _list(paths: List[pathlib.Path]) -> str:
        if not paths:
            return "    # (none)"
        return "\n    ".join(_cmake_path(p) for p in paths)

    return "\n".join([
        "# Auto-generated by reflect_scan.py — do not edit.",
        "set(REFLECT_SCAN_INPUT_FILES",
        f"    {_list(input_files)}",
        ")",
        "set(REFLECT_GEN_HEADERS",
        f"    {_list(out_h_files)}",
        ")",
        "set(REFLECT_GEN_SOURCES",
        f"    {_list(out_cpp_files)}",
        ")",
        f"set(REFLECT_BOOTSTRAP_CPP {_cmake_path(bootstrap_cpp)})",
        f"set(REFLECT_BOOTSTRAP_H   {_cmake_path(bootstrap_h)})",
        "",
    ])


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Batch reflection scanner and code generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--scan-dir",  required=True,
                    help="Directory to scan recursively")
    ap.add_argument("--out-dir",   required=True,
                    help="Output directory for all generated files")
    ap.add_argument("--ext",       default="h",
                    help="Comma-separated extensions to scan (default: h)")
    ap.add_argument("--exclude",   action="append", default=[],
                    help="Glob patterns to exclude (relative to scan-dir). "
                         "May be specified multiple times.")
    ap.add_argument("--bootstrap-func", default="register_all_script_bindings",
                    help="Name of the aggregated registration function")
    ap.add_argument("--bootstrap-out",  default="",
                    help="Path for bootstrap .cpp "
                         "(default: <out-dir>/ReflectionBootstrap.gen.cpp)")
    ap.add_argument("--emit-cmake", default="",
                    help="Write a CMake variable fragment to this path")
    ap.add_argument("--dry-run", action="store_true",
                    help="Text-scan only, no clang. Used at CMake configure time.")
    ap.add_argument("--clangxx",   default="clang++",
                    help="clang++ executable (used in full-codegen mode)")
    ap.add_argument("--std",       default="c++20",
                    help="C++ standard passed to clang++ (default: c++20)")
    ap.add_argument("-I",          dest="includes", action="append", default=[],
                    help="Additional include directories (full-codegen mode)")
    args = ap.parse_args()

    scan_dir = pathlib.Path(args.scan_dir).resolve()
    out_dir  = pathlib.Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    # Default excludes: always skip the output directory itself
    excludes = list(args.exclude) or ["gen/**", "*.gen.*", "*.reflect.*"]

    extensions = [e.strip().lstrip(".") for e in args.ext.split(",") if e.strip()]

    print(f"[reflect_scan] scanning {scan_dir} for extensions: {extensions}")
    candidates = collect_candidates(scan_dir, extensions, excludes)
    print(f"[reflect_scan] found {len(candidates)} annotated file(s)")
    for f in candidates:
        print(f"  {f.relative_to(scan_dir)}")

    # Predict output paths (deterministic, independent of clang)
    out_h_files:   List[pathlib.Path] = []
    out_cpp_files: List[pathlib.Path] = []
    for f in candidates:
        h, cpp = predicted_outputs(out_dir, f)
        out_h_files.append(h)
        out_cpp_files.append(cpp)

    bootstrap_out = (
        pathlib.Path(args.bootstrap_out).resolve()
        if args.bootstrap_out
        else out_dir / "ReflectionBootstrap.gen.cpp"
    )
    bootstrap_h_out = bootstrap_out.with_suffix(".h")

    # Write cmake fragment (both modes)
    if args.emit_cmake:
        cmake_path = pathlib.Path(args.emit_cmake).resolve()
        cmake_path.parent.mkdir(parents=True, exist_ok=True)
        cmake_path.write_text(
            gen_cmake_fragment(
                candidates, out_h_files, out_cpp_files,
                bootstrap_out, bootstrap_h_out,
            ),
            encoding="utf-8",
        )
        print(f"[reflect_scan] cmake fragment written: {cmake_path}")

    if args.dry_run:
        print("[reflect_scan] dry-run complete (no codegen)")
        return 0

    # -----------------------------------------------------------------------
    # Full codegen mode
    # -----------------------------------------------------------------------
    tools_dir    = pathlib.Path(__file__).parent.resolve()
    codegen_tool = tools_dir / "wamr_codegen.py"
    if not codegen_tool.exists():
        print(f"[reflect_scan] error: wamr_codegen.py not found at {codegen_tool}",
              file=sys.stderr)
        return 1

    entries: List[Tuple[str, str]] = []
    errors = 0

    for i, f in enumerate(candidates):
        out_h   = out_h_files[i]
        out_cpp = out_cpp_files[i]
        func    = register_func_name(f.stem)

        print(f"[reflect_scan] codegen: {f.name} → {func}")
        ok = run_codegen(
            codegen_tool, f, out_h, out_cpp, func,
            args.clangxx, args.std, args.includes,
        )
        if ok:
            entries.append((out_h.name, func))
        else:
            print(f"[reflect_scan] error: codegen failed for {f}", file=sys.stderr)
            errors += 1

    # Generate bootstrap
    if entries:
        bootstrap_out.parent.mkdir(parents=True, exist_ok=True)
        bootstrap_out.write_text(
            gen_bootstrap_cpp(entries, args.bootstrap_func),
            encoding="utf-8",
        )
        bootstrap_h_out.write_text(
            gen_bootstrap_h(args.bootstrap_func),
            encoding="utf-8",
        )
        print(f"[reflect_scan] bootstrap cpp: {bootstrap_out}")
        print(f"[reflect_scan] bootstrap hdr: {bootstrap_h_out}")
    else:
        print("[reflect_scan] warning: no types registered — bootstrap not written",
              file=sys.stderr)

    print(f"[reflect_scan] done: {len(entries)} module(s), {errors} error(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"[reflect_scan] fatal: {exc}", file=sys.stderr)
        raise
